apiVersion: 1

datasources:
  - name: SentinelOps Postgres
    uid: sentinelops-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: sentinelops
    user: sentinelops
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: sentinelops
